import './styles/globals.css';
import { Providers } from './redux/providers';
import Layout from './components/template/Layout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout title="SND Admin dashboard" description="Admin dashboard">
          <Providers>{children}</Providers>
        </Layout>
      </body>
    </html>
  );
}
